/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IoButton {
        /**
          * the type of the button
         */
        "appearance": string;
        /**
          * flag for disabling the button
         */
        "disabled": boolean;
        /**
          * the size of the button
         */
        "size": string;
    }
}
declare global {
    interface HTMLIoButtonElement extends Components.IoButton, HTMLStencilElement {
    }
    var HTMLIoButtonElement: {
        prototype: HTMLIoButtonElement;
        new (): HTMLIoButtonElement;
    };
    interface HTMLElementTagNameMap {
        "io-button": HTMLIoButtonElement;
    }
}
declare namespace LocalJSX {
    interface IoButton {
        /**
          * the type of the button
         */
        "appearance"?: string;
        /**
          * flag for disabling the button
         */
        "disabled"?: boolean;
        /**
          * the size of the button
         */
        "size"?: string;
    }
    interface IntrinsicElements {
        "io-button": IoButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "io-button": LocalJSX.IoButton & JSXBase.HTMLAttributes<HTMLIoButtonElement>;
        }
    }
}
