image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:stable

stages:
  - install
  - build
  - release
  - publish

install:
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/node:16.16-alpine
  stage: install
  tags:
    - docker
  only:
    - main
    - tags
  script:
    - npm install
  artifacts:
    paths:
    - node_modules
    expire_in: 1 day

build:
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/node:16.16-alpine
  stage: build
  tags:
    - docker
  dependencies:
    - install
  only:
    - main
    - tags
  script:
    - npx nx build web-components
    - npx nx build web-components-react
    - npx nx build web-components-angular
  artifacts:
    paths:
      - dist
    expire_in: 1 day

release:
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/node:16.16
  stage: release
  tags:
    - docker
  variables:
    GITLAB_TOKEN: ${ACCESS_TOKEN}
    GITLAB_URL: 'https://gitlab.infonline.de'
    GITLAB_PREFIX: '/api/v4'
  before_script:
    - yarn install
    - npm install -g semantic-release@19.0.5
  script:
    - semantic-release
  only:
    - main

publish:web-components:
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/node:16.16-alpine
  tags:
    - docker
  stage: publish
  dependencies:
    - install
    - build
  only:
    - tags
  script:
    - echo ${CI_COMMIT_TAG} | xargs -I {} sed -i 's/0.0.0-development/{}/g' dist/packages/web-components/package.json
    - npm config set @io:registry https://gitlab.infonline.de/api/v4/projects/${CI_PROJECT_ID}/packages/npm/    
    - npm config set -- '//gitlab.infonline.de/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken' ${CI_JOB_TOKEN}
    - cd dist/packages/web-components && npm publish

publish:react-components:
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/node:16.16-alpine
  tags:
    - docker
  stage: publish
  dependencies:
    - install
    - build
  only:
    - tags
  script:
    - echo ${CI_COMMIT_TAG} | xargs -I {} sed -i 's/0.0.0-development/{}/g' dist/packages/web-components-react/package.json
    - npm config set @io:registry https://gitlab.infonline.de/api/v4/projects/${CI_PROJECT_ID}/packages/npm/    
    - npm config set -- '//gitlab.infonline.de/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken' ${CI_JOB_TOKEN}
    - cd dist/packages/web-components-react && npm publish

publish:angular-components:
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/node:16.16-alpine
  tags:
    - docker
  stage: publish
  dependencies:
    - install
    - build
  only:
    - tags
  script:
    - echo ${CI_COMMIT_TAG} | xargs -I {} sed -i 's/0.0.0-development/{}/g' dist/packages/web-components-angular/package.json
    - npm config set @io:registry https://gitlab.infonline.de/api/v4/projects/${CI_PROJECT_ID}/packages/npm/    
    - npm config set -- '//gitlab.infonline.de/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken' ${CI_JOB_TOKEN}
    - cd dist/packages/web-components-angular && npm publish