image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:stable

stages:
  - install
  - build
  - release
  - publish

install:
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/node:16.16-alpine
  stage: install
  tags:
    - docker
  only:
    - main
    - tags
  script:
    - yarn install
  artifacts:
    paths:
    - 'node_modules/'
    expire_in: 1 day

build:
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/node:16.16-alpine
  stage: build
  tags:
    - docker
  dependencies:
    - install
  only:
    - main
    - tags
  script:
    - yarn build
  artifacts:
    paths:
    - 'dist/'
    expire_in: 1 day

release:
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/node:16.16
  stage: release
  tags:
    - docker
  variables:
    GITLAB_TOKEN: ${ACCESS_TOKEN}
    GITLAB_URL: 'https://gitlab.infonline.de'
    GITLAB_PREFIX: '/api/v4'
  before_script:
    - npm install -g semantic-release@19.0.5
  script:
    - semantic-release
  only:
    - main

publish:
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/node:16.16-alpine
  tags:
    - docker
  stage: publish
  dependencies:
    - install
    - build
  only:
    - tags
  script:
    - rm -rf demo src
    - rm tsconfig.json web-dev-server.config.mjs .gitlab-ci.yml .releaserc.json README.md .editorconfig
    - echo ${CI_COMMIT_TAG} | xargs -I {} sed -i 's/0.0.0-development/{}/g' package.json
    - npm config set @io:registry https://gitlab.infonline.de/api/v4/projects/${CI_PROJECT_ID}/packages/npm/    
    - npm config set -- '//gitlab.infonline.de/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken' ${CI_JOB_TOKEN}
    - npm publish