image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:stable

stages:
  - install
  - build
  - release
  - publish

install:web-components:
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/node:16.16-alpine
  stage: install
  tags:
    - docker
  only:
    - main
    - tags
  script:
    - cd web-components
    - yarn install
  artifacts:
    paths:
    - 'web-components'
    expire_in: 1 day

install:react-components:
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/node:16.16-alpine
  stage: install
  tags:
    - docker
  only:
    - main
    - tags
  script:
    - cd react-components
    - yarn install
  artifacts:
    paths:
    - 'react-components/'
    expire_in: 1 day

build:
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/node:16.16-alpine
  stage: build
  tags:
    - docker
  dependencies:
    - install:web-components
    - install:react-components
  only:
    - main
    - tags
  script:
    - cd web-components && yarn build && cd ..
    - cd react-components && yarn build
  artifacts:
    paths:
    - 'web-components/dist'
    - 'react-components/dist'
    expire_in: 1 day

release:
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/node:16.16
  stage: release
  tags:
    - docker
  variables:
    GITLAB_TOKEN: ${ACCESS_TOKEN}
    GITLAB_URL: 'https://gitlab.infonline.de'
    GITLAB_PREFIX: '/api/v4'
  before_script:
    - yarn install
    - npm install -g semantic-release@19.0.5
  script:
    - semantic-release
  only:
    - main

publish:web-components:
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/node:16.16-alpine
  tags:
    - docker
  stage: publish
  dependencies:
    - install:web-components
    - build
  only:
    - tags
  script:
    - echo ${CI_COMMIT_TAG} | xargs -I {} sed -i 's/0.0.0-development/{}/g' web-components/package.json
    - npm config set @io:registry https://gitlab.infonline.de/api/v4/projects/${CI_PROJECT_ID}/packages/npm/    
    - npm config set -- '//gitlab.infonline.de/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken' ${CI_JOB_TOKEN}
    - cd web-components && npm publish

publish:react-components:
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/node:16.16-alpine
  tags:
    - docker
  stage: publish
  dependencies:
    - install:react-components
    - build
  only:
    - tags
  script:
    - echo ${CI_COMMIT_TAG} | xargs -I {} sed -i 's/0.0.0-development/{}/g' react-components/package.json
    - npm config set @io:registry https://gitlab.infonline.de/api/v4/projects/${CI_PROJECT_ID}/packages/npm/    
    - npm config set -- '//gitlab.infonline.de/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken' ${CI_JOB_TOKEN}
    - cd react-components && npm publish