/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IoButton {
        /**
          * the type of the button
         */
        "appearence": string;
        /**
          * the size of the button
         */
        "size": string;
    }
    interface IoInput {
        /**
          * the type of the button
         */
        "type": string;
        /**
          * the value of the button
         */
        "value": string;
    }
}
declare global {
    interface HTMLIoButtonElement extends Components.IoButton, HTMLStencilElement {
    }
    var HTMLIoButtonElement: {
        prototype: HTMLIoButtonElement;
        new (): HTMLIoButtonElement;
    };
    interface HTMLIoInputElement extends Components.IoInput, HTMLStencilElement {
    }
    var HTMLIoInputElement: {
        prototype: HTMLIoInputElement;
        new (): HTMLIoInputElement;
    };
    interface HTMLElementTagNameMap {
        "io-button": HTMLIoButtonElement;
        "io-input": HTMLIoInputElement;
    }
}
declare namespace LocalJSX {
    interface IoButton {
        /**
          * the type of the button
         */
        "appearence"?: string;
        /**
          * the size of the button
         */
        "size"?: string;
    }
    interface IoInput {
        /**
          * the type of the button
         */
        "type"?: string;
        /**
          * the value of the button
         */
        "value"?: string;
    }
    interface IntrinsicElements {
        "io-button": IoButton;
        "io-input": IoInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "io-button": LocalJSX.IoButton & JSXBase.HTMLAttributes<HTMLIoButtonElement>;
            "io-input": LocalJSX.IoInput & JSXBase.HTMLAttributes<HTMLIoInputElement>;
        }
    }
}
